#!/bin/sh

export LOG=/var/log/pcp_jivelite.log

if [ -f /usr/local/etc/pcp/pcp.cfg ]; then
    source /usr/local/etc/pcp/pcp.cfg
    if [ ! -z ${SCREENROTATE} ]; then
        MODEL=$(busybox awk '/^Model/ { print $5 }' /proc/cpuinfo)
        if [ "${MODEL}" == "5" ]; then
            # Rotation CCW=270, UD=180, CW=90 degrees
            if [ "${SCREENROTATE}" == "180" ]; then
                export SDL_VIDEO_FBCON_ROTATION=UD
                export TSLIB_CALIBFILE=/usr/local/etc/pointercal-r2
                echo "Pi5 detected sdl screen rotation enabled." >> $LOG
            fi
        fi
    fi	
fi

if [ ! -z ${JL_FRAME_BUFFER} ]; then
    export SDL_FBDEV=$JL_FRAME_BUFFER
    echo "Using $SDL_FBDEV as frame buffer device." >> $LOG
fi

if [ -z ${JL_FRAME_RATE} ]; then
    JL_FRAME_RATE=22
fi

export JIVE_FRAMERATE=$JL_FRAME_RATE

echo "Frame rate set to $JIVE_FRAMERATE frames per second." >> $LOG

if [ -z ${JL_FRAME_DEPTH} ]; then
    JL_FRAME_DEPTH=32
fi

/usr/sbin/fbset -depth $JL_FRAME_DEPTH >> $LOG
 
echo "Frame buffer color bit depth set to $JL_FRAME_DEPTH." >> $LOG

echo "SDL_TOUCHSCREEN=$SDL_TOUCHSCREEN"

if [ ! -z ${SDL_TOUCHSCREEN} ]; then
    export JIVE_NOCURSOR=1
fi

export HOME=/home/tc

#-- customisation shell script {
# from home directory
TCEMNT="/mnt/$(readlink /etc/sysconfig/tcedir | cut -d '/' -f3)"
TCEDIR="${TCEMNT}/tce"
custom_sh=""
if [ -f /home/tc/jivelite-custom.sh ]; then
    custom_sh="/home/tc/jivelite-custom.sh"
# or from tce
elif [ -f "${TCEDIR}/jivelite-custom.sh" ]; then
    custom_sh="${TCEDIR}/jivelite-custom.sh"
fi

if [ "$custom_sh" != "" ]; then
    echo "Invoking ${custom_sh}" >> $LOG
    source "${custom_sh}" >> $LOG
fi
#-- } customisation shell script


while true; do
    sleep 3
    /opt/jivelite/bin/jivelite >> $LOG 2>&1
done
